spring.application.name=first-restful-app

server.port=9090

#spring.profiles.default=dev

my.welcome.message=Salam

# Enabling H2 Console ? default path is /h2-console
spring.h2.console.enabled=true

# To change the default path to the h2 console
spring.h2.console.path=/h2

# Connection data ? DB is stored in MEMORY
spring.datasource.url=jdbc:h2:mem:restaurantDB
spring.datasource.username=user
spring.datasource.password=pass

# configure connection pool
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10

# configure JPA automatic schema creation
spring.jpa.hibernate.ddl-auto=update

#showing and formatting sql queries as they are executed
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


